
import React, {useState} from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import LeftSide from '@/components/LeftSide'
import RightSide from '@/components/RightSide'
import { motion } from 'framer-motion'
import Banner from '@/components/Banner'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Projects from '@/components/Projects'
import Archive from '@/components/Archive'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import ProjectsTwo from '@/components/works/ProjectsTwo'






const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [open, setOpen] = useState(false);
  


  const introHeaderVariants = {
    hide: {
        opacity: 0,
        x: 200,
    },
    show: {
        opacity: 1,
        x: 0,
        transition: {
            duration: 2,
        },
    },
};
const introPictureVariants = {
  hide: {
      opacity: 0,
      x: 500,
  },
  show: {
      opacity: 1,
      x: 0,
      transition: {
          duration: 2,
      },
  },
};



  return (

    <>
    <Head>
      <title >Josh Levy  </title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/logo.ico'/>
    </Head>
    
    <main className=" w-screen h-screen justify-center font-bodyFont bg-bodyColor text-textLight
    overflow-y-hidden  scrollbar scrollbar-track-textDark/20 overflow-x-hidden
   scrollbar-thumb-textDark/60 mx-auto mainey ">
     <Navbar/>
     <div className=' mx-auto h-[88vh]  xl:flex items-center gap-20 justify-between overflow-x-hidden '>
        
      <motion.div
      initial={{opacity: 0}}
      animate={{opacity:1}}
      transition={{delay:1.5}}
       className='hidden xl:inline-flex w-32 h-full left-0 bottom-0'><LeftSide/></motion.div>
      <div className='h-[88vh] w-full  mx-auto overflow-y-scroll overflow-x-hidden  snap-y snap-mandatory'>
        <div className='snap-start'>
        <Banner/>
        </div>
      <motion.div
      className=' snap-start'
      initial="hide"
      whileInView="show"
      exit="hide"
      variants={introHeaderVariants}>
        {/* about */}
        <About/>
        </motion.div>
        <motion.div
        className='snap-center'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introPictureVariants}>
        {/* experience */}
        <Experience/>
        </motion.div>
        <motion.div
        className='snap-start'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introHeaderVariants}>
        {/* projects */}
        <Projects/>
        </motion.div>
        <motion.div
        className='snap-start'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introHeaderVariants}>
        {/* projects */}
        <ProjectsTwo/>
        </motion.div>
        {/* ARCHIVE SECTION HOLD FOR LATER */}
        {/* <motion.div
        className='snap-center'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introPictureVariants}>
        {/* archive */}
        {/* <Archive/>
        </motion.div> */} 
        <motion.div
        className='snap-center'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introHeaderVariants}>
        {/* contact */}
        <Contact/>
        </motion.div>
        <motion.div
        className='snap-end'
        initial="hide"
        whileInView="show"
        exit="hide"
        variants={introPictureVariants}>
        {/* footer */}
        <Footer/>
        </motion.div>
      </div>
      <motion.div 
      initial={{opacity: 0}}
      animate={{opacity:1}}
      transition={{delay:1.5}}
      className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'>
        <RightSide/>
        </motion.div>
     </div>
    </main>
    </>
  )
  
}
